name: .NET

on:
  push:
    branches: AllHW
  pull_request:
    branches: AllHW

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: | 
          5.0.x
          6.0.x
    - name: Restore dependencies
      run: dotnet restore --packages ./allPackages
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: TestDotMemoryUnit
      run: allPackages\jetbrains.dotmemoryunit\3.2.20220510\lib\tools\dotMemoryUnit.exe "C:\Program Files\dotnet\dotnet.exe" --propagate-exit-code -- test "HomeWork13\Hw13Tests\bin\Release\net6.0\Hw13Tests.dll" 


  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: dotnet test HomeWork13/CachedCalculator/Hw10Tests/Hw10Tests.csproj --logger "trx;LogFileName=test-results.trx"
    - uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: test-results
        path: HomeWork*/CachedCalculator/Hw*Tests/TestResults/*.trx