name: 'Test Report'
on:
  workflow_run:
    workflows: ['.NET']                     # runs after CI workflow
    types:
      - completed
      
permissions:
  statuses: write
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: test-report                  # Name of the check run which will be created
        path: 'TestResults/*.trx'                     # Path to test results (inside artifact .zip)
        reporter: dotnet-trx              # Format of test results
